name: Ensure that 'yarn build' was run before making the pull request

on:
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn
      - name: Build token list
        run: yarn build
      - name: Ensure generated JSON are tokenlists
        run: yarn lint
      - name: Ensure Images are correct type and size
        run: yarn lint-images
      - name: Check if 'yarn build' was run before making the pull request
        run: git diff && git diff-index --quiet HEAD --
